<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Usuario', 'doctrine');

/**
 * BaseUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $usu_codigo
 * @property string $usu_login
 * @property string $usu_password
 * @property Doctrine_Collection $Estudiante
 * @property Doctrine_Collection $Profesor
 * 
 * @method integer             getUsuCodigo()    Returns the current record's "usu_codigo" value
 * @method string              getUsuLogin()     Returns the current record's "usu_login" value
 * @method string              getUsuPassword()  Returns the current record's "usu_password" value
 * @method Doctrine_Collection getEstudiante()   Returns the current record's "Estudiante" collection
 * @method Doctrine_Collection getProfesor()     Returns the current record's "Profesor" collection
 * @method Usuario             setUsuCodigo()    Sets the current record's "usu_codigo" value
 * @method Usuario             setUsuLogin()     Sets the current record's "usu_login" value
 * @method Usuario             setUsuPassword()  Sets the current record's "usu_password" value
 * @method Usuario             setEstudiante()   Sets the current record's "Estudiante" collection
 * @method Usuario             setProfesor()     Sets the current record's "Profesor" collection
 * 
 * @package    OE
 * @subpackage model
 * @author     gaea
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario');
        $this->hasColumn('usu_codigo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'usuario_usu_codigo',
             'length' => 4,
             ));
        $this->hasColumn('usu_login', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('usu_password', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Estudiante', array(
             'local' => 'usu_codigo',
             'foreign' => 'est_codigo_usuario'));

        $this->hasMany('Profesor', array(
             'local' => 'usu_codigo',
             'foreign' => 'pro_codigo_usuario'));
    }
}