<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Herramienta', 'doctrine');

/**
 * BaseHerramienta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $her_codigo
 * @property string $her_nombre
 * @property Doctrine_Collection $PreguntaHerramienta
 * 
 * @method integer             getHerCodigo()           Returns the current record's "her_codigo" value
 * @method string              getHerNombre()           Returns the current record's "her_nombre" value
 * @method Doctrine_Collection getPreguntaHerramienta() Returns the current record's "PreguntaHerramienta" collection
 * @method Herramienta         setHerCodigo()           Sets the current record's "her_codigo" value
 * @method Herramienta         setHerNombre()           Sets the current record's "her_nombre" value
 * @method Herramienta         setPreguntaHerramienta() Sets the current record's "PreguntaHerramienta" collection
 * 
 * @package    OE
 * @subpackage model
 * @author     gaea
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHerramienta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('herramienta');
        $this->hasColumn('her_codigo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'herramienta_her_codigo',
             'length' => 4,
             ));
        $this->hasColumn('her_nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PreguntaHerramienta', array(
             'local' => 'her_codigo',
             'foreign' => 'pre_her_codigo_herramienta'));
    }
}