<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EstudianteSolucionEvaluacionAyuda', 'doctrine');

/**
 * BaseEstudianteSolucionEvaluacionAyuda
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $codigo_estudiante
 * @property integer $codigo_pregunta
 * @property integer $codigo_evaluacion
 * @property Estudiante $Estudiante
 * 
 * @method integer                           getCodigoEstudiante()  Returns the current record's "codigo_estudiante" value
 * @method integer                           getCodigoPregunta()    Returns the current record's "codigo_pregunta" value
 * @method integer                           getCodigoEvaluacion()  Returns the current record's "codigo_evaluacion" value
 * @method Estudiante                        getEstudiante()        Returns the current record's "Estudiante" value
 * @method EstudianteSolucionEvaluacionAyuda setCodigoEstudiante()  Sets the current record's "codigo_estudiante" value
 * @method EstudianteSolucionEvaluacionAyuda setCodigoPregunta()    Sets the current record's "codigo_pregunta" value
 * @method EstudianteSolucionEvaluacionAyuda setCodigoEvaluacion()  Sets the current record's "codigo_evaluacion" value
 * @method EstudianteSolucionEvaluacionAyuda setEstudiante()        Sets the current record's "Estudiante" value
 * 
 * @package    OE
 * @subpackage model
 * @author     gaea
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstudianteSolucionEvaluacionAyuda extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estudiante_solucion_evaluacion_ayuda');
        $this->hasColumn('codigo_estudiante', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('codigo_pregunta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('codigo_evaluacion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Estudiante', array(
             'local' => 'codigo_estudiante',
             'foreign' => 'codigo'));
    }
}