<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EstudianteSolucionEvaluacionPreguntaDispositivo', 'doctrine');

/**
 * BaseEstudianteSolucionEvaluacionPreguntaDispositivo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $est_sol_eva_pre_dis_codigo_estudiante
 * @property integer $est_sol_eva_pre_dis_codigo_pregunta
 * @property integer $est_sol_eva_pre_dis_codigo_evaluacion
 * @property integer $est_sol_eva_pre_dis_codigo_dispositivo
 * @property Dispositivo $Dispositivo
 * 
 * @method integer                                         getId()                                     Returns the current record's "id" value
 * @method integer                                         getEstSolEvaPreDisCodigoEstudiante()        Returns the current record's "est_sol_eva_pre_dis_codigo_estudiante" value
 * @method integer                                         getEstSolEvaPreDisCodigoPregunta()          Returns the current record's "est_sol_eva_pre_dis_codigo_pregunta" value
 * @method integer                                         getEstSolEvaPreDisCodigoEvaluacion()        Returns the current record's "est_sol_eva_pre_dis_codigo_evaluacion" value
 * @method integer                                         getEstSolEvaPreDisCodigoDispositivo()       Returns the current record's "est_sol_eva_pre_dis_codigo_dispositivo" value
 * @method Dispositivo                                     getDispositivo()                            Returns the current record's "Dispositivo" value
 * @method EstudianteSolucionEvaluacionPreguntaDispositivo setId()                                     Sets the current record's "id" value
 * @method EstudianteSolucionEvaluacionPreguntaDispositivo setEstSolEvaPreDisCodigoEstudiante()        Sets the current record's "est_sol_eva_pre_dis_codigo_estudiante" value
 * @method EstudianteSolucionEvaluacionPreguntaDispositivo setEstSolEvaPreDisCodigoPregunta()          Sets the current record's "est_sol_eva_pre_dis_codigo_pregunta" value
 * @method EstudianteSolucionEvaluacionPreguntaDispositivo setEstSolEvaPreDisCodigoEvaluacion()        Sets the current record's "est_sol_eva_pre_dis_codigo_evaluacion" value
 * @method EstudianteSolucionEvaluacionPreguntaDispositivo setEstSolEvaPreDisCodigoDispositivo()       Sets the current record's "est_sol_eva_pre_dis_codigo_dispositivo" value
 * @method EstudianteSolucionEvaluacionPreguntaDispositivo setDispositivo()                            Sets the current record's "Dispositivo" value
 * 
 * @package    OE
 * @subpackage model
 * @author     gaea
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstudianteSolucionEvaluacionPreguntaDispositivo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estudiante_solucion_evaluacion_pregunta_dispositivo');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('est_sol_eva_pre_dis_codigo_estudiante', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('est_sol_eva_pre_dis_codigo_pregunta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('est_sol_eva_pre_dis_codigo_evaluacion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('est_sol_eva_pre_dis_codigo_dispositivo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Dispositivo', array(
             'local' => 'est_sol_eva_pre_dis_codigo_dispositivo',
             'foreign' => 'dis_codigo'));
    }
}