<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Estudiante', 'doctrine');

/**
 * BaseEstudiante
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $est_codigo_usuario
 * @property integer $est_codigo_identificacion
 * @property integer $est_codigo
 * @property string $est_nombres
 * @property string $est_apellidos
 * @property string $est_telefono
 * @property string $est_e_mail
 * @property string $est_url_imagen
 * @property string $est_identificacion
 * @property boolean $est_habilitado
 * @property Identificacion $Identificacion
 * @property Usuario $Usuario
 * @property Doctrine_Collection $EstudianteCurso
 * @property Doctrine_Collection $EstudianteEvaluacionGrupo
 * @property Doctrine_Collection $EstudianteSolucionEvaluacionPregunta
 * 
 * @method integer             getEstCodigoUsuario()                     Returns the current record's "est_codigo_usuario" value
 * @method integer             getEstCodigoIdentificacion()              Returns the current record's "est_codigo_identificacion" value
 * @method integer             getEstCodigo()                            Returns the current record's "est_codigo" value
 * @method string              getEstNombres()                           Returns the current record's "est_nombres" value
 * @method string              getEstApellidos()                         Returns the current record's "est_apellidos" value
 * @method string              getEstTelefono()                          Returns the current record's "est_telefono" value
 * @method string              getEstEMail()                             Returns the current record's "est_e_mail" value
 * @method string              getEstUrlImagen()                         Returns the current record's "est_url_imagen" value
 * @method string              getEstIdentificacion()                    Returns the current record's "est_identificacion" value
 * @method boolean             getEstHabilitado()                        Returns the current record's "est_habilitado" value
 * @method Identificacion      getIdentificacion()                       Returns the current record's "Identificacion" value
 * @method Usuario             getUsuario()                              Returns the current record's "Usuario" value
 * @method Doctrine_Collection getEstudianteCurso()                      Returns the current record's "EstudianteCurso" collection
 * @method Doctrine_Collection getEstudianteEvaluacionGrupo()            Returns the current record's "EstudianteEvaluacionGrupo" collection
 * @method Doctrine_Collection getEstudianteSolucionEvaluacionPregunta() Returns the current record's "EstudianteSolucionEvaluacionPregunta" collection
 * @method Estudiante          setEstCodigoUsuario()                     Sets the current record's "est_codigo_usuario" value
 * @method Estudiante          setEstCodigoIdentificacion()              Sets the current record's "est_codigo_identificacion" value
 * @method Estudiante          setEstCodigo()                            Sets the current record's "est_codigo" value
 * @method Estudiante          setEstNombres()                           Sets the current record's "est_nombres" value
 * @method Estudiante          setEstApellidos()                         Sets the current record's "est_apellidos" value
 * @method Estudiante          setEstTelefono()                          Sets the current record's "est_telefono" value
 * @method Estudiante          setEstEMail()                             Sets the current record's "est_e_mail" value
 * @method Estudiante          setEstUrlImagen()                         Sets the current record's "est_url_imagen" value
 * @method Estudiante          setEstIdentificacion()                    Sets the current record's "est_identificacion" value
 * @method Estudiante          setEstHabilitado()                        Sets the current record's "est_habilitado" value
 * @method Estudiante          setIdentificacion()                       Sets the current record's "Identificacion" value
 * @method Estudiante          setUsuario()                              Sets the current record's "Usuario" value
 * @method Estudiante          setEstudianteCurso()                      Sets the current record's "EstudianteCurso" collection
 * @method Estudiante          setEstudianteEvaluacionGrupo()            Sets the current record's "EstudianteEvaluacionGrupo" collection
 * @method Estudiante          setEstudianteSolucionEvaluacionPregunta() Sets the current record's "EstudianteSolucionEvaluacionPregunta" collection
 * 
 * @package    OE
 * @subpackage model
 * @author     gaea
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstudiante extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estudiante');
        $this->hasColumn('est_codigo_usuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('est_codigo_identificacion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('est_codigo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'estudiante_est_codigo',
             'length' => 4,
             ));
        $this->hasColumn('est_nombres', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('est_apellidos', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('est_telefono', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('est_e_mail', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('est_url_imagen', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('est_identificacion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('est_habilitado', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Identificacion', array(
             'local' => 'est_codigo_identificacion',
             'foreign' => 'ide_codigo'));

        $this->hasOne('Usuario', array(
             'local' => 'est_codigo_usuario',
             'foreign' => 'usu_codigo'));

        $this->hasMany('EstudianteCurso', array(
             'local' => 'est_codigo',
             'foreign' => 'est_cur_codigo_estudiante'));

        $this->hasMany('EstudianteEvaluacionGrupo', array(
             'local' => 'est_codigo',
             'foreign' => 'est_eva_gru_codigo_estudiante'));

        $this->hasMany('EstudianteSolucionEvaluacionPregunta', array(
             'local' => 'est_codigo',
             'foreign' => 'est_sol_eva_pre_codigo_estudiante'));
    }
}