<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Evaluacion', 'doctrine');

/**
 * BaseEvaluacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $eva_codigo
 * @property integer $eva_codigo_profesor
 * @property integer $eva_codigo_tema_materia
 * @property string $eva_nombre
 * @property time $eva_hora_inicio
 * @property time $eva_hora_fin
 * @property integer $eva_numero_personas_grupo
 * @property boolean $eva_publico
 * @property date $eva_fecha
 * @property integer $eva_numero_intentos
 * @property boolean $eva_mostrar_solucion
 * @property boolean $eva_barajar_preguntas
 * @property Profesor $Profesor
 * @property TemaOMateria $TemaOMateria
 * @property Doctrine_Collection $EstudianteEvaluacionGrupo
 * @property Doctrine_Collection $EvaluacionPregunta
 * 
 * @method integer             getEvaCodigo()                 Returns the current record's "eva_codigo" value
 * @method integer             getEvaCodigoProfesor()         Returns the current record's "eva_codigo_profesor" value
 * @method integer             getEvaCodigoTemaMateria()      Returns the current record's "eva_codigo_tema_materia" value
 * @method string              getEvaNombre()                 Returns the current record's "eva_nombre" value
 * @method time                getEvaHoraInicio()             Returns the current record's "eva_hora_inicio" value
 * @method time                getEvaHoraFin()                Returns the current record's "eva_hora_fin" value
 * @method integer             getEvaNumeroPersonasGrupo()    Returns the current record's "eva_numero_personas_grupo" value
 * @method boolean             getEvaPublico()                Returns the current record's "eva_publico" value
 * @method date                getEvaFecha()                  Returns the current record's "eva_fecha" value
 * @method integer             getEvaNumeroIntentos()         Returns the current record's "eva_numero_intentos" value
 * @method boolean             getEvaMostrarSolucion()        Returns the current record's "eva_mostrar_solucion" value
 * @method boolean             getEvaBarajarPreguntas()       Returns the current record's "eva_barajar_preguntas" value
 * @method Profesor            getProfesor()                  Returns the current record's "Profesor" value
 * @method TemaOMateria        getTemaOMateria()              Returns the current record's "TemaOMateria" value
 * @method Doctrine_Collection getEstudianteEvaluacionGrupo() Returns the current record's "EstudianteEvaluacionGrupo" collection
 * @method Doctrine_Collection getEvaluacionPregunta()        Returns the current record's "EvaluacionPregunta" collection
 * @method Evaluacion          setEvaCodigo()                 Sets the current record's "eva_codigo" value
 * @method Evaluacion          setEvaCodigoProfesor()         Sets the current record's "eva_codigo_profesor" value
 * @method Evaluacion          setEvaCodigoTemaMateria()      Sets the current record's "eva_codigo_tema_materia" value
 * @method Evaluacion          setEvaNombre()                 Sets the current record's "eva_nombre" value
 * @method Evaluacion          setEvaHoraInicio()             Sets the current record's "eva_hora_inicio" value
 * @method Evaluacion          setEvaHoraFin()                Sets the current record's "eva_hora_fin" value
 * @method Evaluacion          setEvaNumeroPersonasGrupo()    Sets the current record's "eva_numero_personas_grupo" value
 * @method Evaluacion          setEvaPublico()                Sets the current record's "eva_publico" value
 * @method Evaluacion          setEvaFecha()                  Sets the current record's "eva_fecha" value
 * @method Evaluacion          setEvaNumeroIntentos()         Sets the current record's "eva_numero_intentos" value
 * @method Evaluacion          setEvaMostrarSolucion()        Sets the current record's "eva_mostrar_solucion" value
 * @method Evaluacion          setEvaBarajarPreguntas()       Sets the current record's "eva_barajar_preguntas" value
 * @method Evaluacion          setProfesor()                  Sets the current record's "Profesor" value
 * @method Evaluacion          setTemaOMateria()              Sets the current record's "TemaOMateria" value
 * @method Evaluacion          setEstudianteEvaluacionGrupo() Sets the current record's "EstudianteEvaluacionGrupo" collection
 * @method Evaluacion          setEvaluacionPregunta()        Sets the current record's "EvaluacionPregunta" collection
 * 
 * @package    OE
 * @subpackage model
 * @author     gaea
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvaluacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('evaluacion');
        $this->hasColumn('eva_codigo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'evaluacion_eva_codigo',
             'length' => 4,
             ));
        $this->hasColumn('eva_codigo_profesor', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('eva_codigo_tema_materia', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('eva_nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('eva_hora_inicio', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('eva_hora_fin', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('eva_numero_personas_grupo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('eva_publico', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('eva_fecha', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('eva_numero_intentos', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('eva_mostrar_solucion', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
        $this->hasColumn('eva_barajar_preguntas', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profesor', array(
             'local' => 'eva_codigo_profesor',
             'foreign' => 'pro_codigo'));

        $this->hasOne('TemaOMateria', array(
             'local' => 'eva_codigo_tema_materia',
             'foreign' => 'tom_codigo'));

        $this->hasMany('EstudianteEvaluacionGrupo', array(
             'local' => 'eva_codigo',
             'foreign' => 'est_eva_gru_codigo_evaluacion'));

        $this->hasMany('EvaluacionPregunta', array(
             'local' => 'eva_codigo',
             'foreign' => 'eva_pre_codigo_evaluacion'));
    }
}