<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EstudianteSolucionEvaluacion', 'doctrine');

/**
 * BaseEstudianteSolucionEvaluacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $codigo_estudiante
 * @property integer $codigo_pregunta
 * @property integer $codigo_evaluacion
 * @property integer $codigo_ayuda
 * @property Ayuda $Ayuda
 * 
 * @method integer                      getId()                Returns the current record's "id" value
 * @method integer                      getCodigoEstudiante()  Returns the current record's "codigo_estudiante" value
 * @method integer                      getCodigoPregunta()    Returns the current record's "codigo_pregunta" value
 * @method integer                      getCodigoEvaluacion()  Returns the current record's "codigo_evaluacion" value
 * @method integer                      getCodigoAyuda()       Returns the current record's "codigo_ayuda" value
 * @method Ayuda                        getAyuda()             Returns the current record's "Ayuda" value
 * @method EstudianteSolucionEvaluacion setId()                Sets the current record's "id" value
 * @method EstudianteSolucionEvaluacion setCodigoEstudiante()  Sets the current record's "codigo_estudiante" value
 * @method EstudianteSolucionEvaluacion setCodigoPregunta()    Sets the current record's "codigo_pregunta" value
 * @method EstudianteSolucionEvaluacion setCodigoEvaluacion()  Sets the current record's "codigo_evaluacion" value
 * @method EstudianteSolucionEvaluacion setCodigoAyuda()       Sets the current record's "codigo_ayuda" value
 * @method EstudianteSolucionEvaluacion setAyuda()             Sets the current record's "Ayuda" value
 * 
 * @package    OE
 * @subpackage model
 * @author     gaea
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstudianteSolucionEvaluacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estudiante_solucion_evaluacion');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('codigo_estudiante', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('codigo_pregunta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('codigo_evaluacion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('codigo_ayuda', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Ayuda', array(
             'local' => 'codigo_ayuda',
             'foreign' => 'codigo'));
    }
}