<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Estudiante', 'doctrine');

/**
 * BaseEstudiante
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $codigo_usuario
 * @property integer $codigo_identificacion
 * @property integer $codigo
 * @property Usuario $Usuario
 * @property Identificacion $Identificacion
 * @property Doctrine_Collection $EstudianteCurso
 * @property Doctrine_Collection $EstudianteEvaluacionGrupo
 * @property Doctrine_Collection $EstudianteSolucionEvaluacionAyuda
 * 
 * @method integer             getCodigoUsuario()                     Returns the current record's "codigo_usuario" value
 * @method integer             getCodigoIdentificacion()              Returns the current record's "codigo_identificacion" value
 * @method integer             getCodigo()                            Returns the current record's "codigo" value
 * @method Usuario             getUsuario()                           Returns the current record's "Usuario" value
 * @method Identificacion      getIdentificacion()                    Returns the current record's "Identificacion" value
 * @method Doctrine_Collection getEstudianteCurso()                   Returns the current record's "EstudianteCurso" collection
 * @method Doctrine_Collection getEstudianteEvaluacionGrupo()         Returns the current record's "EstudianteEvaluacionGrupo" collection
 * @method Doctrine_Collection getEstudianteSolucionEvaluacionAyuda() Returns the current record's "EstudianteSolucionEvaluacionAyuda" collection
 * @method Estudiante          setCodigoUsuario()                     Sets the current record's "codigo_usuario" value
 * @method Estudiante          setCodigoIdentificacion()              Sets the current record's "codigo_identificacion" value
 * @method Estudiante          setCodigo()                            Sets the current record's "codigo" value
 * @method Estudiante          setUsuario()                           Sets the current record's "Usuario" value
 * @method Estudiante          setIdentificacion()                    Sets the current record's "Identificacion" value
 * @method Estudiante          setEstudianteCurso()                   Sets the current record's "EstudianteCurso" collection
 * @method Estudiante          setEstudianteEvaluacionGrupo()         Sets the current record's "EstudianteEvaluacionGrupo" collection
 * @method Estudiante          setEstudianteSolucionEvaluacionAyuda() Sets the current record's "EstudianteSolucionEvaluacionAyuda" collection
 * 
 * @package    OE
 * @subpackage model
 * @author     gaea
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstudiante extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estudiante');
        $this->hasColumn('codigo_usuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('codigo_identificacion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('codigo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'estudiante_codigo',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Usuario', array(
             'local' => 'codigo_usuario',
             'foreign' => 'codigo'));

        $this->hasOne('Identificacion', array(
             'local' => 'codigo_identificacion',
             'foreign' => 'codigo'));

        $this->hasMany('EstudianteCurso', array(
             'local' => 'codigo',
             'foreign' => 'codigo'));

        $this->hasMany('EstudianteEvaluacionGrupo', array(
             'local' => 'codigo',
             'foreign' => 'codigo'));

        $this->hasMany('EstudianteSolucionEvaluacionAyuda', array(
             'local' => 'codigo',
             'foreign' => 'codigo_estudiante'));
    }
}