<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EstudianteSolucionEvaluacionPreguntaAyuda', 'doctrine');

/**
 * BaseEstudianteSolucionEvaluacionPreguntaAyuda
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $est_sol_eva_pre_ayu_codigo_estudiante
 * @property integer $est_sol_eva_pre_ayu_codigo_pregunta
 * @property integer $est_sol_eva_pre_ayu_codigo_evaluacion
 * @property integer $est_sol_eva_pre_ayu_codigo_ayuda
 * @property Ayuda $Ayuda
 * 
 * @method integer                                   getId()                                    Returns the current record's "id" value
 * @method integer                                   getEstSolEvaPreAyuCodigoEstudiante()       Returns the current record's "est_sol_eva_pre_ayu_codigo_estudiante" value
 * @method integer                                   getEstSolEvaPreAyuCodigoPregunta()         Returns the current record's "est_sol_eva_pre_ayu_codigo_pregunta" value
 * @method integer                                   getEstSolEvaPreAyuCodigoEvaluacion()       Returns the current record's "est_sol_eva_pre_ayu_codigo_evaluacion" value
 * @method integer                                   getEstSolEvaPreAyuCodigoAyuda()            Returns the current record's "est_sol_eva_pre_ayu_codigo_ayuda" value
 * @method Ayuda                                     getAyuda()                                 Returns the current record's "Ayuda" value
 * @method EstudianteSolucionEvaluacionPreguntaAyuda setId()                                    Sets the current record's "id" value
 * @method EstudianteSolucionEvaluacionPreguntaAyuda setEstSolEvaPreAyuCodigoEstudiante()       Sets the current record's "est_sol_eva_pre_ayu_codigo_estudiante" value
 * @method EstudianteSolucionEvaluacionPreguntaAyuda setEstSolEvaPreAyuCodigoPregunta()         Sets the current record's "est_sol_eva_pre_ayu_codigo_pregunta" value
 * @method EstudianteSolucionEvaluacionPreguntaAyuda setEstSolEvaPreAyuCodigoEvaluacion()       Sets the current record's "est_sol_eva_pre_ayu_codigo_evaluacion" value
 * @method EstudianteSolucionEvaluacionPreguntaAyuda setEstSolEvaPreAyuCodigoAyuda()            Sets the current record's "est_sol_eva_pre_ayu_codigo_ayuda" value
 * @method EstudianteSolucionEvaluacionPreguntaAyuda setAyuda()                                 Sets the current record's "Ayuda" value
 * 
 * @package    OE
 * @subpackage model
 * @author     gaea
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstudianteSolucionEvaluacionPreguntaAyuda extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estudiante_solucion_evaluacion_pregunta_ayuda');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('est_sol_eva_pre_ayu_codigo_estudiante', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('est_sol_eva_pre_ayu_codigo_pregunta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('est_sol_eva_pre_ayu_codigo_evaluacion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('est_sol_eva_pre_ayu_codigo_ayuda', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Ayuda', array(
             'local' => 'est_sol_eva_pre_ayu_codigo_ayuda',
             'foreign' => 'ayu_codigo'));
    }
}