<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Usuario', 'doctrine');

/**
 * BaseUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $codigo
 * @property string $login
 * @property string $password
 * @property Doctrine_Collection $Estudiante
 * @property Doctrine_Collection $Profesor
 * 
 * @method integer             getCodigo()     Returns the current record's "codigo" value
 * @method string              getLogin()      Returns the current record's "login" value
 * @method string              getPassword()   Returns the current record's "password" value
 * @method Doctrine_Collection getEstudiante() Returns the current record's "Estudiante" collection
 * @method Doctrine_Collection getProfesor()   Returns the current record's "Profesor" collection
 * @method Usuario             setCodigo()     Sets the current record's "codigo" value
 * @method Usuario             setLogin()      Sets the current record's "login" value
 * @method Usuario             setPassword()   Sets the current record's "password" value
 * @method Usuario             setEstudiante() Sets the current record's "Estudiante" collection
 * @method Usuario             setProfesor()   Sets the current record's "Profesor" collection
 * 
 * @package    OE
 * @subpackage model
 * @author     gaea
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario');
        $this->hasColumn('codigo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'usuario_codigo',
             'length' => 4,
             ));
        $this->hasColumn('login', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('password', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Estudiante', array(
             'local' => 'codigo',
             'foreign' => 'codigo_usuario'));

        $this->hasMany('Profesor', array(
             'local' => 'codigo',
             'foreign' => 'codigo_usuario'));
    }
}