<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EstudianteEvaluacionGrupo', 'doctrine');

/**
 * BaseEstudianteEvaluacionGrupo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $est_eva_gru_codigo_estudiante
 * @property integer $est_eva_gru_codigo_evaluacion
 * @property integer $est_eva_gru_numero_grupo
 * @property Evaluacion $Evaluacion
 * @property Estudiante $Estudiante
 * 
 * @method integer                   getId()                            Returns the current record's "id" value
 * @method integer                   getEstEvaGruCodigoEstudiante()     Returns the current record's "est_eva_gru_codigo_estudiante" value
 * @method integer                   getEstEvaGruCodigoEvaluacion()     Returns the current record's "est_eva_gru_codigo_evaluacion" value
 * @method integer                   getEstEvaGruNumeroGrupo()          Returns the current record's "est_eva_gru_numero_grupo" value
 * @method Evaluacion                getEvaluacion()                    Returns the current record's "Evaluacion" value
 * @method Estudiante                getEstudiante()                    Returns the current record's "Estudiante" value
 * @method EstudianteEvaluacionGrupo setId()                            Sets the current record's "id" value
 * @method EstudianteEvaluacionGrupo setEstEvaGruCodigoEstudiante()     Sets the current record's "est_eva_gru_codigo_estudiante" value
 * @method EstudianteEvaluacionGrupo setEstEvaGruCodigoEvaluacion()     Sets the current record's "est_eva_gru_codigo_evaluacion" value
 * @method EstudianteEvaluacionGrupo setEstEvaGruNumeroGrupo()          Sets the current record's "est_eva_gru_numero_grupo" value
 * @method EstudianteEvaluacionGrupo setEvaluacion()                    Sets the current record's "Evaluacion" value
 * @method EstudianteEvaluacionGrupo setEstudiante()                    Sets the current record's "Estudiante" value
 * 
 * @package    OE
 * @subpackage model
 * @author     gaea
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstudianteEvaluacionGrupo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estudiante_evaluacion_grupo');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('est_eva_gru_codigo_estudiante', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('est_eva_gru_codigo_evaluacion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('est_eva_gru_numero_grupo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Evaluacion', array(
             'local' => 'est_eva_gru_codigo_evaluacion',
             'foreign' => 'eva_codigo'));

        $this->hasOne('Estudiante', array(
             'local' => 'est_eva_gru_codigo_estudiante',
             'foreign' => 'est_codigo'));
    }
}