<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Ayuda', 'doctrine');

/**
 * BaseAyuda
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $codigo
 * @property string $nombre
 * @property decimal $penalizacion
 * @property string $cuerpo
 * @property Doctrine_Collection $EstudianteSolucionEvaluacion
 * @property Doctrine_Collection $EvaluacionPreguntaAyuda
 * 
 * @method integer             getCodigo()                       Returns the current record's "codigo" value
 * @method string              getNombre()                       Returns the current record's "nombre" value
 * @method decimal             getPenalizacion()                 Returns the current record's "penalizacion" value
 * @method string              getCuerpo()                       Returns the current record's "cuerpo" value
 * @method Doctrine_Collection getEstudianteSolucionEvaluacion() Returns the current record's "EstudianteSolucionEvaluacion" collection
 * @method Doctrine_Collection getEvaluacionPreguntaAyuda()      Returns the current record's "EvaluacionPreguntaAyuda" collection
 * @method Ayuda               setCodigo()                       Sets the current record's "codigo" value
 * @method Ayuda               setNombre()                       Sets the current record's "nombre" value
 * @method Ayuda               setPenalizacion()                 Sets the current record's "penalizacion" value
 * @method Ayuda               setCuerpo()                       Sets the current record's "cuerpo" value
 * @method Ayuda               setEstudianteSolucionEvaluacion() Sets the current record's "EstudianteSolucionEvaluacion" collection
 * @method Ayuda               setEvaluacionPreguntaAyuda()      Sets the current record's "EvaluacionPreguntaAyuda" collection
 * 
 * @package    OE
 * @subpackage model
 * @author     gaea
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAyuda extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ayuda');
        $this->hasColumn('codigo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'ayuda_codigo',
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('penalizacion', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('cuerpo', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('EstudianteSolucionEvaluacion', array(
             'local' => 'codigo',
             'foreign' => 'codigo_ayuda'));

        $this->hasMany('EvaluacionPreguntaAyuda', array(
             'local' => 'codigo',
             'foreign' => 'codigo_ayuda'));
    }
}