<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Identificacion', 'doctrine');

/**
 * BaseIdentificacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ide_codigo
 * @property string $ide_tipo
 * @property Doctrine_Collection $Estudiante
 * @property Doctrine_Collection $Profesor
 * 
 * @method integer             getIdeCodigo()  Returns the current record's "ide_codigo" value
 * @method string              getIdeTipo()    Returns the current record's "ide_tipo" value
 * @method Doctrine_Collection getEstudiante() Returns the current record's "Estudiante" collection
 * @method Doctrine_Collection getProfesor()   Returns the current record's "Profesor" collection
 * @method Identificacion      setIdeCodigo()  Sets the current record's "ide_codigo" value
 * @method Identificacion      setIdeTipo()    Sets the current record's "ide_tipo" value
 * @method Identificacion      setEstudiante() Sets the current record's "Estudiante" collection
 * @method Identificacion      setProfesor()   Sets the current record's "Profesor" collection
 * 
 * @package    OE
 * @subpackage model
 * @author     gaea
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIdentificacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('identificacion');
        $this->hasColumn('ide_codigo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'identificacion_ide_codigo',
             'length' => 4,
             ));
        $this->hasColumn('ide_tipo', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Estudiante', array(
             'local' => 'ide_codigo',
             'foreign' => 'est_codigo_identificacion'));

        $this->hasMany('Profesor', array(
             'local' => 'ide_codigo',
             'foreign' => 'pro_codigo_identificacion'));
    }
}