<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EvaluacionPregunta', 'doctrine');

/**
 * BaseEvaluacionPregunta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $eva_pre_codigo_evaluacion
 * @property integer $eva_pre_codigo_pregunta
 * @property Pregunta $Pregunta
 * @property Evaluacion $Evaluacion
 * 
 * @method integer            getEvaPreCodigoEvaluacion()    Returns the current record's "eva_pre_codigo_evaluacion" value
 * @method integer            getEvaPreCodigoPregunta()      Returns the current record's "eva_pre_codigo_pregunta" value
 * @method Pregunta           getPregunta()                  Returns the current record's "Pregunta" value
 * @method Evaluacion         getEvaluacion()                Returns the current record's "Evaluacion" value
 * @method EvaluacionPregunta setEvaPreCodigoEvaluacion()    Sets the current record's "eva_pre_codigo_evaluacion" value
 * @method EvaluacionPregunta setEvaPreCodigoPregunta()      Sets the current record's "eva_pre_codigo_pregunta" value
 * @method EvaluacionPregunta setPregunta()                  Sets the current record's "Pregunta" value
 * @method EvaluacionPregunta setEvaluacion()                Sets the current record's "Evaluacion" value
 * 
 * @package    OE
 * @subpackage model
 * @author     gaea
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvaluacionPregunta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('evaluacion_pregunta');
        $this->hasColumn('eva_pre_codigo_evaluacion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('eva_pre_codigo_pregunta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Pregunta', array(
             'local' => 'eva_pre_codigo_pregunta',
             'foreign' => 'pre_codigo'));

        $this->hasOne('Evaluacion', array(
             'local' => 'eva_pre_codigo_evaluacion',
             'foreign' => 'eva_codigo'));
    }
}