<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Curso', 'doctrine');

/**
 * BaseCurso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cur_codigo_profesor
 * @property string $cur_nombre
 * @property integer $cur_codigo
 * @property date $cur_fecha_creacion
 * @property boolean $cur_habilitado
 * @property Profesor $Profesor
 * @property Doctrine_Collection $EstudianteCurso
 * 
 * @method integer             getCurCodigoProfesor()   Returns the current record's "cur_codigo_profesor" value
 * @method string              getCurNombre()           Returns the current record's "cur_nombre" value
 * @method integer             getCurCodigo()           Returns the current record's "cur_codigo" value
 * @method date                getCurFechaCreacion()    Returns the current record's "cur_fecha_creacion" value
 * @method boolean             getCurHabilitado()       Returns the current record's "cur_habilitado" value
 * @method Profesor            getProfesor()            Returns the current record's "Profesor" value
 * @method Doctrine_Collection getEstudianteCurso()     Returns the current record's "EstudianteCurso" collection
 * @method Curso               setCurCodigoProfesor()   Sets the current record's "cur_codigo_profesor" value
 * @method Curso               setCurNombre()           Sets the current record's "cur_nombre" value
 * @method Curso               setCurCodigo()           Sets the current record's "cur_codigo" value
 * @method Curso               setCurFechaCreacion()    Sets the current record's "cur_fecha_creacion" value
 * @method Curso               setCurHabilitado()       Sets the current record's "cur_habilitado" value
 * @method Curso               setProfesor()            Sets the current record's "Profesor" value
 * @method Curso               setEstudianteCurso()     Sets the current record's "EstudianteCurso" collection
 * 
 * @package    OE
 * @subpackage model
 * @author     gaea
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCurso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('curso');
        $this->hasColumn('cur_codigo_profesor', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('cur_nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('cur_codigo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'curso_cur_codigo',
             'length' => 4,
             ));
        $this->hasColumn('cur_fecha_creacion', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 25,
             ));
        $this->hasColumn('cur_habilitado', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profesor', array(
             'local' => 'cur_codigo_profesor',
             'foreign' => 'pro_codigo'));

        $this->hasMany('EstudianteCurso', array(
             'local' => 'cur_codigo',
             'foreign' => 'est_cur_codigo_curso'));
    }
}