<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Ayuda', 'doctrine');

/**
 * BaseAyuda
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ayu_codigo
 * @property string $ayu_nombre
 * @property decimal $ayu_penalizacion
 * @property string $ayu_cuerpo
 * @property Doctrine_Collection $EstudianteSolucionEvaluacionPreguntaAyuda
 * @property Doctrine_Collection $EvaluacionPreguntaAyuda
 * 
 * @method integer             getAyuCodigo()                                 Returns the current record's "ayu_codigo" value
 * @method string              getAyuNombre()                                 Returns the current record's "ayu_nombre" value
 * @method decimal             getAyuPenalizacion()                           Returns the current record's "ayu_penalizacion" value
 * @method string              getAyuCuerpo()                                 Returns the current record's "ayu_cuerpo" value
 * @method Doctrine_Collection getEstudianteSolucionEvaluacionPreguntaAyuda() Returns the current record's "EstudianteSolucionEvaluacionPreguntaAyuda" collection
 * @method Doctrine_Collection getEvaluacionPreguntaAyuda()                   Returns the current record's "EvaluacionPreguntaAyuda" collection
 * @method Ayuda               setAyuCodigo()                                 Sets the current record's "ayu_codigo" value
 * @method Ayuda               setAyuNombre()                                 Sets the current record's "ayu_nombre" value
 * @method Ayuda               setAyuPenalizacion()                           Sets the current record's "ayu_penalizacion" value
 * @method Ayuda               setAyuCuerpo()                                 Sets the current record's "ayu_cuerpo" value
 * @method Ayuda               setEstudianteSolucionEvaluacionPreguntaAyuda() Sets the current record's "EstudianteSolucionEvaluacionPreguntaAyuda" collection
 * @method Ayuda               setEvaluacionPreguntaAyuda()                   Sets the current record's "EvaluacionPreguntaAyuda" collection
 * 
 * @package    OE
 * @subpackage model
 * @author     gaea
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAyuda extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ayuda');
        $this->hasColumn('ayu_codigo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'ayuda_ayu_codigo',
             'length' => 4,
             ));
        $this->hasColumn('ayu_nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('ayu_penalizacion', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 18,
             ));
        $this->hasColumn('ayu_cuerpo', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('EstudianteSolucionEvaluacionPreguntaAyuda', array(
             'local' => 'ayu_codigo',
             'foreign' => 'est_sol_eva_pre_ayu_codigo_ayuda'));

        $this->hasMany('EvaluacionPreguntaAyuda', array(
             'local' => 'ayu_codigo',
             'foreign' => 'eva_pre_ayu_codigo_ayuda'));
    }
}