<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EstudianteSolucionEvaluacionPregunta', 'doctrine');

/**
 * BaseEstudianteSolucionEvaluacionPregunta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $est_sol_eva_pre_codigo_estudiante
 * @property integer $est_sol_eva_pre_codigo_pregunta
 * @property integer $est_sol_eva_pre_codigo_evaluacion
 * @property Estudiante $Estudiante
 * 
 * @method integer                              getEstSolEvaPreCodigoEstudiante()      Returns the current record's "est_sol_eva_pre_codigo_estudiante" value
 * @method integer                              getEstSolEvaPreCodigoPregunta()        Returns the current record's "est_sol_eva_pre_codigo_pregunta" value
 * @method integer                              getEstSolEvaPreCodigoEvaluacion()      Returns the current record's "est_sol_eva_pre_codigo_evaluacion" value
 * @method Estudiante                           getEstudiante()                        Returns the current record's "Estudiante" value
 * @method EstudianteSolucionEvaluacionPregunta setEstSolEvaPreCodigoEstudiante()      Sets the current record's "est_sol_eva_pre_codigo_estudiante" value
 * @method EstudianteSolucionEvaluacionPregunta setEstSolEvaPreCodigoPregunta()        Sets the current record's "est_sol_eva_pre_codigo_pregunta" value
 * @method EstudianteSolucionEvaluacionPregunta setEstSolEvaPreCodigoEvaluacion()      Sets the current record's "est_sol_eva_pre_codigo_evaluacion" value
 * @method EstudianteSolucionEvaluacionPregunta setEstudiante()                        Sets the current record's "Estudiante" value
 * 
 * @package    OE
 * @subpackage model
 * @author     gaea
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstudianteSolucionEvaluacionPregunta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estudiante_solucion_evaluacion_pregunta');
        $this->hasColumn('est_sol_eva_pre_codigo_estudiante', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('est_sol_eva_pre_codigo_pregunta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('est_sol_eva_pre_codigo_evaluacion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Estudiante', array(
             'local' => 'est_sol_eva_pre_codigo_estudiante',
             'foreign' => 'est_codigo'));
    }
}