<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Herramienta', 'doctrine');

/**
 * BaseHerramienta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $codigo
 * @property string $nombre
 * @property Doctrine_Collection $PreguntaHerramienta
 * 
 * @method integer             getCodigo()              Returns the current record's "codigo" value
 * @method string              getNombre()              Returns the current record's "nombre" value
 * @method Doctrine_Collection getPreguntaHerramienta() Returns the current record's "PreguntaHerramienta" collection
 * @method Herramienta         setCodigo()              Sets the current record's "codigo" value
 * @method Herramienta         setNombre()              Sets the current record's "nombre" value
 * @method Herramienta         setPreguntaHerramienta() Sets the current record's "PreguntaHerramienta" collection
 * 
 * @package    OE
 * @subpackage model
 * @author     gaea
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHerramienta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('herramienta');
        $this->hasColumn('codigo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'herramienta_codigo',
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PreguntaHerramienta', array(
             'local' => 'codigo',
             'foreign' => 'codigo_herramienta'));
    }
}