<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Dispositivo', 'doctrine');

/**
 * BaseDispositivo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $dis_codigo
 * @property string $nombre
 * @property Doctrine_Collection $EstudianteSolucionEvaluacionPreguntaDispositivo
 * 
 * @method integer             getDisCodigo()                                       Returns the current record's "dis_codigo" value
 * @method string              getNombre()                                          Returns the current record's "nombre" value
 * @method Doctrine_Collection getEstudianteSolucionEvaluacionPreguntaDispositivo() Returns the current record's "EstudianteSolucionEvaluacionPreguntaDispositivo" collection
 * @method Dispositivo         setDisCodigo()                                       Sets the current record's "dis_codigo" value
 * @method Dispositivo         setNombre()                                          Sets the current record's "nombre" value
 * @method Dispositivo         setEstudianteSolucionEvaluacionPreguntaDispositivo() Sets the current record's "EstudianteSolucionEvaluacionPreguntaDispositivo" collection
 * 
 * @package    OE
 * @subpackage model
 * @author     gaea
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDispositivo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dispositivo');
        $this->hasColumn('dis_codigo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'dispositivo_dis_codigo',
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('EstudianteSolucionEvaluacionPreguntaDispositivo', array(
             'local' => 'dis_codigo',
             'foreign' => 'est_sol_eva_pre_dis_codigo_dispositivo'));
    }
}