<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TemaOMateria', 'doctrine');

/**
 * BaseTemaOMateria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tom_codigo
 * @property string $tom_nombre
 * @property Doctrine_Collection $Evaluacion
 * @property Doctrine_Collection $Pregunta
 * 
 * @method integer             getTomCodigo()  Returns the current record's "tom_codigo" value
 * @method string              getTomNombre()  Returns the current record's "tom_nombre" value
 * @method Doctrine_Collection getEvaluacion() Returns the current record's "Evaluacion" collection
 * @method Doctrine_Collection getPregunta()   Returns the current record's "Pregunta" collection
 * @method TemaOMateria        setTomCodigo()  Sets the current record's "tom_codigo" value
 * @method TemaOMateria        setTomNombre()  Sets the current record's "tom_nombre" value
 * @method TemaOMateria        setEvaluacion() Sets the current record's "Evaluacion" collection
 * @method TemaOMateria        setPregunta()   Sets the current record's "Pregunta" collection
 * 
 * @package    OE
 * @subpackage model
 * @author     gaea
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTemaOMateria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tema_o_materia');
        $this->hasColumn('tom_codigo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'tema_o_materia_tom_codigo',
             'length' => 4,
             ));
        $this->hasColumn('tom_nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Evaluacion', array(
             'local' => 'tom_codigo',
             'foreign' => 'eva_codigo_tema_materia'));

        $this->hasMany('Pregunta', array(
             'local' => 'tom_codigo',
             'foreign' => 'pre_codigo_tema_o_materia'));
    }
}