<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EstudianteCurso', 'doctrine');

/**
 * BaseEstudianteCurso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $est_cur_codigo_curso
 * @property integer $est_cur_codigo_estudiante
 * @property Estudiante $Estudiante
 * @property Curso $Curso
 * 
 * @method integer         getEstCurCodigoCurso()         Returns the current record's "est_cur_codigo_curso" value
 * @method integer         getEstCurCodigoEstudiante()    Returns the current record's "est_cur_codigo_estudiante" value
 * @method Estudiante      getEstudiante()                Returns the current record's "Estudiante" value
 * @method Curso           getCurso()                     Returns the current record's "Curso" value
 * @method EstudianteCurso setEstCurCodigoCurso()         Sets the current record's "est_cur_codigo_curso" value
 * @method EstudianteCurso setEstCurCodigoEstudiante()    Sets the current record's "est_cur_codigo_estudiante" value
 * @method EstudianteCurso setEstudiante()                Sets the current record's "Estudiante" value
 * @method EstudianteCurso setCurso()                     Sets the current record's "Curso" value
 * 
 * @package    OE
 * @subpackage model
 * @author     gaea
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstudianteCurso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estudiante_curso');
        $this->hasColumn('est_cur_codigo_curso', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('est_cur_codigo_estudiante', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Estudiante', array(
             'local' => 'est_cur_codigo_estudiante',
             'foreign' => 'est_codigo'));

        $this->hasOne('Curso', array(
             'local' => 'est_cur_codigo_curso',
             'foreign' => 'cur_codigo'));
    }
}