<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Curso', 'doctrine');

/**
 * BaseCurso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $codigo
 * @property string $nombre
 * @property Profesor $Profesor
 * @property Doctrine_Collection $EstudianteCurso
 * 
 * @method integer             getCodigo()          Returns the current record's "codigo" value
 * @method string              getNombre()          Returns the current record's "nombre" value
 * @method Profesor            getProfesor()        Returns the current record's "Profesor" value
 * @method Doctrine_Collection getEstudianteCurso() Returns the current record's "EstudianteCurso" collection
 * @method Curso               setCodigo()          Sets the current record's "codigo" value
 * @method Curso               setNombre()          Sets the current record's "nombre" value
 * @method Curso               setProfesor()        Sets the current record's "Profesor" value
 * @method Curso               setEstudianteCurso() Sets the current record's "EstudianteCurso" collection
 * 
 * @package    OE
 * @subpackage model
 * @author     gaea
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCurso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('curso');
        $this->hasColumn('codigo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profesor', array(
             'local' => 'codigo',
             'foreign' => 'codigo'));

        $this->hasMany('EstudianteCurso', array(
             'local' => 'codigo',
             'foreign' => 'codigo_curso'));
    }
}