<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EstudianteEvaluacionGrupo', 'doctrine');

/**
 * BaseEstudianteEvaluacionGrupo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $codigo
 * @property integer $eva_codigo
 * @property Evaluacion $Evaluacion
 * @property Estudiante $Estudiante
 * 
 * @method integer                   getId()         Returns the current record's "id" value
 * @method integer                   getCodigo()     Returns the current record's "codigo" value
 * @method integer                   getEvaCodigo()  Returns the current record's "eva_codigo" value
 * @method Evaluacion                getEvaluacion() Returns the current record's "Evaluacion" value
 * @method Estudiante                getEstudiante() Returns the current record's "Estudiante" value
 * @method EstudianteEvaluacionGrupo setId()         Sets the current record's "id" value
 * @method EstudianteEvaluacionGrupo setCodigo()     Sets the current record's "codigo" value
 * @method EstudianteEvaluacionGrupo setEvaCodigo()  Sets the current record's "eva_codigo" value
 * @method EstudianteEvaluacionGrupo setEvaluacion() Sets the current record's "Evaluacion" value
 * @method EstudianteEvaluacionGrupo setEstudiante() Sets the current record's "Estudiante" value
 * 
 * @package    OE
 * @subpackage model
 * @author     gaea
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstudianteEvaluacionGrupo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estudiante_evaluacion_grupo');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('codigo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('eva_codigo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Evaluacion', array(
             'local' => 'eva_codigo',
             'foreign' => 'codigo'));

        $this->hasOne('Estudiante', array(
             'local' => 'codigo',
             'foreign' => 'codigo'));
    }
}