<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TipoPregunta', 'doctrine');

/**
 * BaseTipoPregunta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $codigo
 * @property string $nombre
 * @property string $plantilla
 * @property Doctrine_Collection $Pregunta
 * 
 * @method integer             getCodigo()    Returns the current record's "codigo" value
 * @method string              getNombre()    Returns the current record's "nombre" value
 * @method string              getPlantilla() Returns the current record's "plantilla" value
 * @method Doctrine_Collection getPregunta()  Returns the current record's "Pregunta" collection
 * @method TipoPregunta        setCodigo()    Sets the current record's "codigo" value
 * @method TipoPregunta        setNombre()    Sets the current record's "nombre" value
 * @method TipoPregunta        setPlantilla() Sets the current record's "plantilla" value
 * @method TipoPregunta        setPregunta()  Sets the current record's "Pregunta" collection
 * 
 * @package    OE
 * @subpackage model
 * @author     gaea
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoPregunta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_pregunta');
        $this->hasColumn('codigo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'tipo_pregunta_codigo',
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('plantilla', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Pregunta', array(
             'local' => 'codigo',
             'foreign' => 'codigo_tipo_pregunta'));
    }
}