<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TipoPregunta', 'doctrine');

/**
 * BaseTipoPregunta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tip_pre_codigo
 * @property string $tip_pre_nombre
 * @property string $tip_pre_plantilla
 * @property Doctrine_Collection $Pregunta
 * 
 * @method integer             getTipPreCodigo()      Returns the current record's "tip_pre_codigo" value
 * @method string              getTipPreNombre()      Returns the current record's "tip_pre_nombre" value
 * @method string              getTipPrePlantilla()   Returns the current record's "tip_pre_plantilla" value
 * @method Doctrine_Collection getPregunta()          Returns the current record's "Pregunta" collection
 * @method TipoPregunta        setTipPreCodigo()      Sets the current record's "tip_pre_codigo" value
 * @method TipoPregunta        setTipPreNombre()      Sets the current record's "tip_pre_nombre" value
 * @method TipoPregunta        setTipPrePlantilla()   Sets the current record's "tip_pre_plantilla" value
 * @method TipoPregunta        setPregunta()          Sets the current record's "Pregunta" collection
 * 
 * @package    OE
 * @subpackage model
 * @author     gaea
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoPregunta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_pregunta');
        $this->hasColumn('tip_pre_codigo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'tipo_pregunta_tip_pre_codigo',
             'length' => 4,
             ));
        $this->hasColumn('tip_pre_nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('tip_pre_plantilla', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Pregunta', array(
             'local' => 'tip_pre_codigo',
             'foreign' => 'pre_codigo_tipo_pregunta'));
    }
}