<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/02/16 11:54:09

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=OE',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
