<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/02/24 11:03:50

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=oe',
  'username' => 'oe',
  'password' => 'oe',
  'name' => 'doctrine',
)),);
