<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/02/24 16:05:33
sfConfig::add(array(
  'mod_gestion_plugins_enabled' => true,
  'mod_gestion_plugins_view_class' => 'sfPHP',
));
