<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/02/17 17:42:29
sfConfig::add(array(
  'mod_gestion_profesores_enabled' => true,
  'mod_gestion_profesores_view_class' => 'sfPHP',
));
