<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/04/06 18:27:52
sfConfig::add(array(
  'mod_gestion_cursos_enabled' => true,
  'mod_gestion_cursos_view_class' => 'sfPHP',
));
