<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/02/17 11:58:02
sfConfig::add(array(
  'mod_gestion_estudiantes_enabled' => true,
  'mod_gestion_estudiantes_view_class' => 'sfPHP',
));
