<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/02/21 16:22:02
sfConfig::add(array(
  'mod_gestion_profesores_enabled' => true,
  'mod_gestion_profesores_view_class' => 'sfPHP',
));
