<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/02/12 19:55:19
sfConfig::add(array(
  'mod_interfaz_administracion_enabled' => true,
  'mod_interfaz_administracion_view_class' => 'sfPHP',
));
