<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/03/27 14:44:19
sfConfig::add(array(
  'mod_gestion_estudiantes_enabled' => true,
  'mod_gestion_estudiantes_view_class' => 'sfPHP',
));
