<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/04/02 16:21:51
sfConfig::add(array(
  'mod_gestion_cursos_enabled' => true,
  'mod_gestion_cursos_view_class' => 'sfPHP',
));
