<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/04/02 16:26:02
sfConfig::add(array(
  'mod_maestra_identificacion_enabled' => true,
  'mod_maestra_identificacion_view_class' => 'sfPHP',
));
