<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/02/21 11:44:00
sfConfig::add(array(
  'mod_interfaz_administracion_enabled' => true,
  'mod_interfaz_administracion_view_class' => 'sfPHP',
));
