<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/02/24 15:08:12
sfConfig::add(array(
  'mod_maestra_identificacion_enabled' => true,
  'mod_maestra_identificacion_view_class' => 'sfPHP',
));
