<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/04/01 20:39:33
sfConfig::add(array(
  'mod_gestion_plugins_enabled' => true,
  'mod_gestion_plugins_view_class' => 'sfPHP',
));
