<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/02/18 20:58:41
sfConfig::add(array(
  'mod_gestion_profesores_enabled' => true,
  'mod_gestion_profesores_view_class' => 'sfPHP',
));
