<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/04/01 20:39:29
sfConfig::add(array(
  'mod_gestion_estudiantes_enabled' => true,
  'mod_gestion_estudiantes_view_class' => 'sfPHP',
));
