<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/02/21 16:22:06
sfConfig::add(array(
  'mod_maestra_identificacion_enabled' => true,
  'mod_maestra_identificacion_view_class' => 'sfPHP',
));
