tema_o_materia_maestra_tema_o_materia:
  class: sfDoctrineRouteCollection
  options:
    model:                TemaOMateria
    module:               maestra_tema_o_materia
    prefix_path:          /maestra_tema_o_materia
    column:               tom_codigo
    with_wildcard_routes: true

tema_o_materia:
  class: sfDoctrineRouteCollection
  options:
    model:                TemaOMateria
    module:               admin_tema_o_materia
    prefix_path:          /admin_tema_o_materia
    column:               tom_codigo
    with_wildcard_routes: true


identificacion:
  class: sfDoctrineRouteCollection
  options:
    model:                Identificacion
    module:               maestra_identificacion
    prefix_path:          /maestra_identificacion
    column:               ide_codigo
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
