<?php

/**
 * Estudiante
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    OE
 * @subpackage model
 * @author     gaea
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Estudiante extends BaseEstudiante
{
}
