<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/06/14 18:35:03

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=oe',
  'username' => 'oe',
  'password' => 'oe',
  'name' => 'doctrine',
)),);
