<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/14 18:41:23
sfConfig::add(array(
  'mod_interfaz_profesor_enabled' => true,
  'mod_interfaz_profesor_view_class' => 'sfPHP',
));
