<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/03/23 15:12:56
sfConfig::add(array(
  'mod_interfaz_profesor_enabled' => true,
  'mod_interfaz_profesor_view_class' => 'sfPHP',
));
