<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/12 20:46:05
sfConfig::add(array(
  'mod_login_profesor_enabled' => true,
  'mod_login_profesor_view_class' => 'sfPHP',
));
