<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/14 18:35:13
sfConfig::add(array(
  'mod_login_profesor_enabled' => true,
  'mod_login_profesor_view_class' => 'sfPHP',
));
