<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/04/11 10:22:08

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=oe',
  'username' => 'oe',
  'password' => 'oe',
  'name' => 'doctrine',
)),);
