<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/02/24 16:08:22
sfConfig::add(array(
  'mod_gestion_estudiantes_enabled' => true,
  'mod_gestion_estudiantes_view_class' => 'sfPHP',
));
