<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/14 19:48:00
sfConfig::add(array(
  'mod_interfaz_administracion_enabled' => true,
  'mod_interfaz_administracion_view_class' => 'sfPHP',
));
