<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/04/11 10:22:14
sfConfig::add(array(
  'mod_gestion_estudiantes_enabled' => true,
  'mod_gestion_estudiantes_view_class' => 'sfPHP',
));
