<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/02/18 16:50:53
sfConfig::add(array(
  'mod_interfaz_administracion_enabled' => true,
  'mod_interfaz_administracion_view_class' => 'sfPHP',
));
