<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/02/18 16:50:54
sfConfig::add(array(
  'mod_gestion_profesores_enabled' => true,
  'mod_gestion_profesores_view_class' => 'sfPHP',
));
