<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/16 23:18:42
sfConfig::add(array(
  'mod_admin_tema_o_materia_enabled' => true,
  'mod_admin_tema_o_materia_view_class' => 'sfPHP',
));
