<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/16 23:24:13
sfConfig::add(array(
  'mod_maestra_identificacion_enabled' => true,
  'mod_maestra_identificacion_view_class' => 'sfPHP',
));
