<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/04/04 10:44:48
sfConfig::add(array(
  'mod_gestion_cursos_enabled' => true,
  'mod_gestion_cursos_view_class' => 'sfPHP',
));
