<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/16 23:19:33
sfConfig::add(array(
  'mod_maestra_tema_o_materia_enabled' => true,
  'mod_maestra_tema_o_materia_view_class' => 'sfPHP',
));
