<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/03/28 11:54:46
sfConfig::add(array(
  'mod_interfaz_administracion_enabled' => true,
  'mod_interfaz_administracion_view_class' => 'sfPHP',
));
