<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/02/24 16:08:18
sfConfig::add(array(
  'mod_gestion_profesores_enabled' => true,
  'mod_gestion_profesores_view_class' => 'sfPHP',
));
