<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/02/23 11:34:38
sfConfig::add(array(
  'mod_maestra_identificacion_enabled' => true,
  'mod_maestra_identificacion_view_class' => 'sfPHP',
));
