<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/03/28 11:54:50
sfConfig::add(array(
  'mod_gestion_cursos_enabled' => true,
  'mod_gestion_cursos_view_class' => 'sfPHP',
));
