<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/02/28 09:42:16
sfConfig::add(array(
  'mod_maestra_identificacion_enabled' => true,
  'mod_maestra_identificacion_view_class' => 'sfPHP',
));
