<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/06/08 22:33:01
sfConfig::add(array(
  'mod_gestion_cursos_enabled' => true,
  'mod_gestion_cursos_view_class' => 'sfPHP',
));
