Ayuda:
  connection: doctrine
  tableName: ayuda
  columns:
    ayu_codigo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      sequence: ayuda_ayu_codigo
    ayu_nombre:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    ayu_penalizacion:
      type: decimal(18)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    ayu_cuerpo:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
  relations:
    EstudianteSolucionEvaluacionPreguntaAyuda:
      local: ayu_codigo
      foreign: est_sol_eva_pre_ayu_codigo_ayuda
      type: many
    EvaluacionPreguntaAyuda:
      local: ayu_codigo
      foreign: eva_pre_ayu_codigo_ayuda
      type: many
Curso:
  connection: doctrine
  tableName: curso
  columns:
    cur_codigo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
    cur_nombre:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
  relations:
    Profesor:
      local: cur_codigo
      foreign: pro_codigo
      type: one
    EstudianteCurso:
      local: cur_codigo
      foreign: est_cur_codigo_curso
      type: many
Dispositivo:
  connection: doctrine
  tableName: dispositivo
  columns:
    dis_codigo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      sequence: dispositivo_dis_codigo
    nombre:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
  relations:
    EstudianteSolucionEvaluacionPreguntaDispositivo:
      local: dis_codigo
      foreign: est_sol_eva_pre_dis_codigo_dispositivo
      type: many
Estudiante:
  connection: doctrine
  tableName: estudiante
  columns:
    est_codigo_usuario:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    est_codigo_identificacion:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    est_codigo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      sequence: estudiante_est_codigo
    est_nombres:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    est_apellidos:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    est_telefono:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    est_e_mail:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    est_habilitado:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    est_url_imagen:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    est_identificacion:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
  relations:
    Usuario:
      local: est_codigo_usuario
      foreign: usu_codigo
      type: one
    Identificacion:
      local: est_codigo_identificacion
      foreign: ide_codigo
      type: one
    EstudianteCurso:
      local: est_codigo
      foreign: est_cur_codigo_estudiante
      type: many
    EstudianteEvaluacionGrupo:
      local: est_codigo
      foreign: est_eva_gru_codigo_estudiante
      type: many
    EstudianteSolucionEvaluacionPregunta:
      local: est_codigo
      foreign: est_sol_eva_pre_codigo_estudiante
      type: many
EstudianteCurso:
  connection: doctrine
  tableName: estudiante_curso
  columns:
    est_cur_codigo_curso:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
    est_cur_codigo_estudiante:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
  relations:
    Curso:
      local: est_cur_codigo_curso
      foreign: cur_codigo
      type: one
    Estudiante:
      local: est_cur_codigo_estudiante
      foreign: est_codigo
      type: one
EstudianteEvaluacionGrupo:
  connection: doctrine
  tableName: estudiante_evaluacion_grupo
  columns:
    id:
      type: integer(8)
      autoincrement: true
      primary: true
    est_eva_gru_codigo_estudiante:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    est_eva_gru_codigo_evaluacion:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    est_eva_gru_numero_grupo:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
  relations:
    Evaluacion:
      local: est_eva_gru_codigo_evaluacion
      foreign: eva_codigo
      type: one
    Estudiante:
      local: est_eva_gru_codigo_estudiante
      foreign: est_codigo
      type: one
EstudianteSolucionEvaluacionPregunta:
  connection: doctrine
  tableName: estudiante_solucion_evaluacion_pregunta
  columns:
    est_sol_eva_pre_codigo_estudiante:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
    est_sol_eva_pre_codigo_pregunta:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
    est_sol_eva_pre_codigo_evaluacion:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
  relations:
    Estudiante:
      local: est_sol_eva_pre_codigo_estudiante
      foreign: est_codigo
      type: one
EstudianteSolucionEvaluacionPreguntaAyuda:
  connection: doctrine
  tableName: estudiante_solucion_evaluacion_pregunta_ayuda
  columns:
    id:
      type: integer(8)
      autoincrement: true
      primary: true
    est_sol_eva_pre_ayu_codigo_estudiante:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    est_sol_eva_pre_ayu_codigo_pregunta:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    est_sol_eva_pre_ayu_codigo_evaluacion:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    est_sol_eva_pre_ayu_codigo_ayuda:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
  relations:
    Ayuda:
      local: est_sol_eva_pre_ayu_codigo_ayuda
      foreign: ayu_codigo
      type: one
EstudianteSolucionEvaluacionPreguntaDispositivo:
  connection: doctrine
  tableName: estudiante_solucion_evaluacion_pregunta_dispositivo
  columns:
    id:
      type: integer(8)
      autoincrement: true
      primary: true
    est_sol_eva_pre_dis_codigo_estudiante:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    est_sol_eva_pre_dis_codigo_pregunta:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    est_sol_eva_pre_dis_codigo_evaluacion:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    est_sol_eva_pre_dis_codigo_dispositivo:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
  relations:
    Dispositivo:
      local: est_sol_eva_pre_dis_codigo_dispositivo
      foreign: dis_codigo
      type: one
Evaluacion:
  connection: doctrine
  tableName: evaluacion
  columns:
    eva_codigo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      sequence: evaluacion_eva_codigo
    eva_codigo_profesor:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    eva_codigo_tema_materia:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    eva_nombre:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    eva_hora_inicio:
      type: time(25)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    eva_hora_fin:
      type: time(25)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    eva_numero_personas_grupo:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    eva_publico:
      type: boolean(1)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    eva_fecha:
      type: date(25)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    eva_numero_intentos:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    eva_mostrar_solucion:
      type: boolean(1)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    eva_barajar_preguntas:
      type: boolean(1)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
  relations:
    Profesor:
      local: eva_codigo_profesor
      foreign: pro_codigo
      type: one
    TemaOMateria:
      local: eva_codigo_tema_materia
      foreign: tom_codigo
      type: one
    EstudianteEvaluacionGrupo:
      local: eva_codigo
      foreign: est_eva_gru_codigo_evaluacion
      type: many
    EvaluacionPregunta:
      local: eva_codigo
      foreign: eva_pre_codigo_evaluacion
      type: many
EvaluacionPregunta:
  connection: doctrine
  tableName: evaluacion_pregunta
  columns:
    eva_pre_codigo_evaluacion:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
    eva_pre_codigo_pregunta:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
  relations:
    Pregunta:
      local: eva_pre_codigo_pregunta
      foreign: pre_codigo
      type: one
    Evaluacion:
      local: eva_pre_codigo_evaluacion
      foreign: eva_codigo
      type: one
EvaluacionPreguntaAyuda:
  connection: doctrine
  tableName: evaluacion_pregunta_ayuda
  columns:
    id:
      type: integer(8)
      autoincrement: true
      primary: true
    eva_pre_ayu_codigo_evaluacion:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    eva_pre_ayu_codigo_pregunta:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    eva_pre_ayu_codigo_ayuda:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
  relations:
    Ayuda:
      local: eva_pre_ayu_codigo_ayuda
      foreign: ayu_codigo
      type: one
Herramienta:
  connection: doctrine
  tableName: herramienta
  columns:
    her_codigo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      sequence: herramienta_her_codigo
    her_nombre:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
  relations:
    PreguntaHerramienta:
      local: her_codigo
      foreign: pre_her_codigo_herramienta
      type: many
Identificacion:
  connection: doctrine
  tableName: identificacion
  columns:
    ide_codigo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      sequence: identificacion_ide_codigo
    ide_tipo:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
  relations:
    Estudiante:
      local: ide_codigo
      foreign: est_codigo_identificacion
      type: many
    Profesor:
      local: ide_codigo
      foreign: pro_codigo_identificacion
      type: many
Pregunta:
  connection: doctrine
  tableName: pregunta
  columns:
    pre_codigo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      sequence: pregunta_pre_codigo
    pre_codigo_profesor:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    pre_codigo_tema_o_materia:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    pre_codigo_tipo_pregunta:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    pre_cuerpo:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    pre_solucion:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    pre_publico:
      type: boolean(1)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
  relations:
    TemaOMateria:
      local: pre_codigo_tema_o_materia
      foreign: tom_codigo
      type: one
    Profesor:
      local: pre_codigo_profesor
      foreign: pro_codigo
      type: one
    TipoPregunta:
      local: pre_codigo_tipo_pregunta
      foreign: tip_pre_codigo
      type: one
    EvaluacionPregunta:
      local: pre_codigo
      foreign: eva_pre_codigo_pregunta
      type: many
    PreguntaHerramienta:
      local: pre_codigo
      foreign: pre_her_codigo_pregunta
      type: many
PreguntaHerramienta:
  connection: doctrine
  tableName: pregunta_herramienta
  columns:
    id:
      type: integer(8)
      autoincrement: true
      primary: true
    pre_her_codigo_herramienta:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
    pre_her_codigo_pregunta:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: true
      primary: false
  relations:
    Herramienta:
      local: pre_her_codigo_herramienta
      foreign: her_codigo
      type: one
    Pregunta:
      local: pre_her_codigo_pregunta
      foreign: pre_codigo
      type: one
Profesor:
  connection: doctrine
  tableName: profesor
  columns:
    pro_codigo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      sequence: profesor_pro_codigo
    pro_codigo_usuario:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    pro_codigo_identificacion:
      type: integer(4)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    pro_nombres:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    pro_apellidos:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    pro_telefono:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    pro_e_mail:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    pro_habilitado:
      type: boolean(1)
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    pro_url_imagen:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    pro_identificacion:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
  relations:
    Usuario:
      local: pro_codigo_usuario
      foreign: usu_codigo
      type: one
    Identificacion:
      local: pro_codigo_identificacion
      foreign: ide_codigo
      type: one
    Curso:
      local: pro_codigo
      foreign: cur_codigo
      type: many
    Evaluacion:
      local: pro_codigo
      foreign: eva_codigo_profesor
      type: many
    Pregunta:
      local: pro_codigo
      foreign: pre_codigo_profesor
      type: many
TemaOMateria:
  connection: doctrine
  tableName: tema_o_materia
  columns:
    tom_codigo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      sequence: tema_o_materia_tom_codigo
    tom_nombre:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
  relations:
    Evaluacion:
      local: tom_codigo
      foreign: eva_codigo_tema_materia
      type: many
    Pregunta:
      local: tom_codigo
      foreign: pre_codigo_tema_o_materia
      type: many
TipoPregunta:
  connection: doctrine
  tableName: tipo_pregunta
  columns:
    tip_pre_codigo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      sequence: tipo_pregunta_tip_pre_codigo
    tip_pre_nombre:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    tip_pre_plantilla:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
  relations:
    Pregunta:
      local: tip_pre_codigo
      foreign: pre_codigo_tipo_pregunta
      type: many
Usuario:
  connection: doctrine
  tableName: usuario
  columns:
    usu_codigo:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      sequence: usuario_usu_codigo
    usu_login:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
    usu_password:
      type: string()
      fixed: false
      unsigned: false
      notnull: false
      primary: false
  relations:
    Estudiante:
      local: usu_codigo
      foreign: est_codigo_usuario
      type: many
    Profesor:
      local: usu_codigo
      foreign: pro_codigo_usuario
      type: many
